window:
  padding:
    x: 10
    y: 10
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.9

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Roboto Mono Nerd Font
    style:  Regular
  bold:
    family: Roboto Mono Nerd Font
    style:  Bold
  italic:
    family: Roboto Mono Nerd Font
    style:  Italic
  bold_italic:
    family: Roboto Mono Nerd Font
    style: Bold Italic
  size: 9
draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: "0x2f343f"
    foreground: "0xd3dae3"
  normal:
    black: "0x4b5164"
    red: "0xe14245"
    green: "0x5ca75b"
    yellow: "0xf6ab32"
    blue: "0x4877b1"
    magenta: "0xa660c3"
    cyan: "0x5294e2"
    white: "0xa9a9aa"
  bright:
    black: "0x616981"
    red: "0xe16f7e"
    green: "0xadd488"
    yellow: "0xfdc35f"
    blue: "0x8ca9bf"
    magenta: "0xe2afec"
    cyan: "0x73c5e2"
    white: "0xfcfcfc"
  dim:
    black:   '0x2c2f3a'
    red:     '0x783228'
    green:   '0x4b7c16'
    yellow:  '0xb65619'
    blue:    '0x2b486b'
    magenta: '0x614a73'
    cyan:    '0x1b668f'
    white:   '0x63686d'

shell:
    program: /usr/bin/fish

